---
title: "README"
output: github_document
date: "2025-02-26"
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile,
                          encoding = encoding, 
                          output_dir = here::here())
      })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

pacman::p_load(tidyverse,
               sf)
```

## README

README file for codominance project

## File description

```{r}
df_fnm <- tibble(file = c("`code/analysis_q1.R`",
                           "`code/format_data.R`",
                           "`code/map_mode.R`",
                           "`code/allTraits_mergeFile.R`",
                           "`code/sample_gawdist`"),
                  note = c("multinomial model relating # of codominance to envrionmental variables",
                           "entry point of data formatting; combining all codominance data.",
                           "generating source information for GIS",
                           "getting all trait data together",
                           "sample code for calculating dendrogram trait distance `gawdist()`"))

knitr::kable(df_fnm)
```

